stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - cache/uniprot_sprot.xml.gz:
          cache: false
  process:
    cmd: bash/convert cache/uniprot_sprot.xml.gz xsl/uniprot.xsl cache/uniprot_sprot.csv
    deps:
      - bash/convert
      - xsl/uniprot.xsl
      - cache/uniprot_sprot.xml.gz
    outs:
      - cache/uniprot_sprot.csv:
          cache: false
  csv_to_parquet:
    cmd: Rscript R/csv_to_parquet.R
    deps:
      - cache/uniprot_sprot.csv
    outs:
      - data/uniprot_sprot.parquet